/// Flutter icons WicomIconos
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WicomIconos
///      fonts:
///       - asset: fonts/WicomIconos.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WicomIconos {
  WicomIconos._();

  static const _kFontFam = 'WicomIconos';
  static const _kFontPkg = null;

  static const IconData icono = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconocalificar = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconohome = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconolupa = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
